INSERT INTO [dbo].[Buz_Device]([F_Id],[F_DeviceName],[F_ParentId],[F_DeviceId],[F_DeviceProperties],[F_DeviceTypeId],[F_Brand],[F_Model],[F_HardwareVersion],[F_SoftwareVersion],[F_Producer],[F_ProductTime],[F_DeployTime],[F_StatusId],[F_Description],[F_CreatorTime],[F_CreatorUserId],[F_LastModifyTime],[F_LastModifyUserId],[F_DeleteMark],[F_DeleteTime],[F_DeleteUserId]) VALUES (NEWID(),N'Smart Lock',N'0',NEWID(),N'',N'4e8af0c4-2f17-4803-bd36-00e327303829',N'Mi',N'10000',N'41.3.2500',N'34.6.3900',N'XiaoMi',GETDATE(),GETDATE(),N'4dd9daee-c3ad-422e-b582-beab34f61371',N'Neque porro qusit amet, consectetur, ad l.',GETDATE(),N'Ernest4',null,null,0,null,null)
INSERT INTO [dbo].[Buz_Device]([F_Id],[F_DeviceName],[F_ParentId],[F_DeviceId],[F_DeviceProperties],[F_DeviceTypeId],[F_Brand],[F_Model],[F_HardwareVersion],[F_SoftwareVersion],[F_Producer],[F_ProductTime],[F_DeployTime],[F_StatusId],[F_Description],[F_CreatorTime],[F_CreatorUserId],[F_LastModifyTime],[F_LastModifyUserId],[F_DeleteMark],[F_DeleteTime],[F_DeleteUserId]) VALUES (NEWID(),N'Smart Lock',N'0',NEWID(),N'',N'4e8af0c4-2f17-4803-bd36-00e327303829',N'Mi',N'10-100',N'47.0.1100',N'13.1.9700',N'XiaoMi',GETDATE(),GETDATE(),N'4dd9daee-c3ad-422e-b582-beab34f61371',N'Sed ut perspiciateritexplicabo.',GETDATE(),N'Gilbert4',null,null,0,null,null)
INSERT INTO [dbo].[Buz_Device]([F_Id],[F_DeviceName],[F_ParentId],[F_DeviceId],[F_DeviceProperties],[F_DeviceTypeId],[F_Brand],[F_Model],[F_HardwareVersion],[F_SoftwareVersion],[F_Producer],[F_ProductTime],[F_DeployTime],[F_StatusId],[F_Description],[F_CreatorTime],[F_CreatorUserId],[F_LastModifyTime],[F_LastModifyUserId],[F_DeleteMark],[F_DeleteTime],[F_DeleteUserId]) VALUES (NEWID(),N'Smart Lock',N'0',NEWID(),N'',N'4e8af0c4-2f17-4803-bd36-00e327303829',N'Mi',N'10000',N'41.3.2500',N'34.6.3900',N'XiaoMi',GETDATE(),GETDATE(),N'4dd9daee-c3ad-422e-b582-beab34f61371',N'Neque porro qusit amet, consectetur, ad l.',GETDATE(),N'Ernest4',null,null,0,null,null)

INSERT INTO [dbo].[Buz_Device]([F_Id],[F_DeviceName],[F_ParentId],[F_DeviceId],[F_DeviceProperties],[F_DeviceTypeId],[F_Brand],[F_Model],[F_HardwareVersion],[F_SoftwareVersion],[F_Producer],[F_ProductTime],[F_DeployTime],[F_StatusId],[F_Description],[F_CreatorTime],[F_CreatorUserId],[F_LastModifyTime],[F_LastModifyUserId],[F_DeleteMark],[F_DeleteTime],[F_DeleteUserId]) VALUES (NEWID(),N'Elec Meter',N'0',NEWID(),N'',N'ab2b78ad-9ead-4f8d-94b0-e93db5064a89',N'JSY',N'10-100',N'41.3.2500',N'34.6.3900',N'JSY',GETDATE(),GETDATE(),N'4dd9daee-c3ad-422e-b582-beab34f61371',N'Neque porro qusit amet, consectetur, ad l.',GETDATE(),N'Ernest4',null,null,0,null,null)
INSERT INTO [dbo].[Buz_Device]([F_Id],[F_DeviceName],[F_ParentId],[F_DeviceId],[F_DeviceProperties],[F_DeviceTypeId],[F_Brand],[F_Model],[F_HardwareVersion],[F_SoftwareVersion],[F_Producer],[F_ProductTime],[F_DeployTime],[F_StatusId],[F_Description],[F_CreatorTime],[F_CreatorUserId],[F_LastModifyTime],[F_LastModifyUserId],[F_DeleteMark],[F_DeleteTime],[F_DeleteUserId]) VALUES (NEWID(),N'Elec Meter',N'0',NEWID(),N'',N'ab2b78ad-9ead-4f8d-94b0-e93db5064a89',N'JSY',N'10-100',N'47.0.1100',N'13.1.9700',N'JSY',GETDATE(),GETDATE(),N'4dd9daee-c3ad-422e-b582-beab34f61371',N'Sed ut perspiciateritexplicabo.',GETDATE(),N'Gilbert4',null,null,0,null,null)
INSERT INTO [dbo].[Buz_Device]([F_Id],[F_DeviceName],[F_ParentId],[F_DeviceId],[F_DeviceProperties],[F_DeviceTypeId],[F_Brand],[F_Model],[F_HardwareVersion],[F_SoftwareVersion],[F_Producer],[F_ProductTime],[F_DeployTime],[F_StatusId],[F_Description],[F_CreatorTime],[F_CreatorUserId],[F_LastModifyTime],[F_LastModifyUserId],[F_DeleteMark],[F_DeleteTime],[F_DeleteUserId]) VALUES (NEWID(),N'Elec Meter',N'0',NEWID(),N'',N'ab2b78ad-9ead-4f8d-94b0-e93db5064a89',N'JSY',N'10-100',N'41.3.2500',N'34.6.3900',N'JSY',GETDATE(),GETDATE(),N'4dd9daee-c3ad-422e-b582-beab34f61371',N'Neque porro qusit amet, consectetur, ad l.',GETDATE(),N'Ernest4',null,null,0,null,null)

INSERT INTO [dbo].[Buz_Device]([F_Id],[F_DeviceName],[F_ParentId],[F_DeviceId],[F_DeviceProperties],[F_DeviceTypeId],[F_Brand],[F_Model],[F_HardwareVersion],[F_SoftwareVersion],[F_Producer],[F_ProductTime],[F_DeployTime],[F_StatusId],[F_Description],[F_CreatorTime],[F_CreatorUserId],[F_LastModifyTime],[F_LastModifyUserId],[F_DeleteMark],[F_DeleteTime],[F_DeleteUserId]) VALUES (NEWID(),N'Water Meter',N'0',NEWID(),N'',N'45bba7ba-646f-44b0-b518-d3edf65db2a1',N'JSY',N'20-100',N'41.3.2500',N'34.6.3900',N'JSY',GETDATE(),GETDATE(),N'4dd9daee-c3ad-422e-b582-beab34f61371',N'Neque porro qusit amet, consectetur, ad l.',GETDATE(),N'Ernest4',null,null,0,null,null)
INSERT INTO [dbo].[Buz_Device]([F_Id],[F_DeviceName],[F_ParentId],[F_DeviceId],[F_DeviceProperties],[F_DeviceTypeId],[F_Brand],[F_Model],[F_HardwareVersion],[F_SoftwareVersion],[F_Producer],[F_ProductTime],[F_DeployTime],[F_StatusId],[F_Description],[F_CreatorTime],[F_CreatorUserId],[F_LastModifyTime],[F_LastModifyUserId],[F_DeleteMark],[F_DeleteTime],[F_DeleteUserId]) VALUES (NEWID(),N'Water Meter',N'0',NEWID(),N'',N'45bba7ba-646f-44b0-b518-d3edf65db2a1',N'JSY',N'20-100',N'47.0.1100',N'13.1.9700',N'JSY',GETDATE(),GETDATE(),N'4dd9daee-c3ad-422e-b582-beab34f61371',N'Sed ut perspiciateritexplicabo.',GETDATE(),N'Gilbert4',null,null,0,null,null)
INSERT INTO [dbo].[Buz_Device]([F_Id],[F_DeviceName],[F_ParentId],[F_DeviceId],[F_DeviceProperties],[F_DeviceTypeId],[F_Brand],[F_Model],[F_HardwareVersion],[F_SoftwareVersion],[F_Producer],[F_ProductTime],[F_DeployTime],[F_StatusId],[F_Description],[F_CreatorTime],[F_CreatorUserId],[F_LastModifyTime],[F_LastModifyUserId],[F_DeleteMark],[F_DeleteTime],[F_DeleteUserId]) VALUES (NEWID(),N'Water Meter',N'0',NEWID(),N'',N'45bba7ba-646f-44b0-b518-d3edf65db2a1',N'JSY',N'20-100',N'41.3.2500',N'34.6.3900',N'JSY',GETDATE(),GETDATE(),N'4dd9daee-c3ad-422e-b582-beab34f61371',N'Neque porro qusit amet, consectetur, ad l.',GETDATE(),N'Ernest4',null,null,0,null,null)
